#!/usr/bin/env python3
"""
Automation script for nano-train development workflow.

This script helps automate:
1. Push local code changes to GitHub
2. Pull latest code in Google Colab

Usage:
    ./scripts/sync_and_run.sh    # Push local changes, then run Colab
"""

import os
import subprocess
import sys
from pathlib import Path
from datetime import datetime


def run_command(cmd, description=""):
    """Run a command and print output."""
    print(f"🔄 {description}")
    result = subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print(f"✅ {description} - SUCCESS")
        if result.stdout:
            print(result.stdout)
    else:
        print(f"❌ {description} - FAILED")
        if result.stderr:
            print(result.stderr)


def check_git_changes():
    """Check if there are uncommitted git changes."""
    result = subprocess.run(
        ['git', 'status', '--porcelain'],
        capture_output=True,
        text=True
    )

    # Check if there are changes
    has_changes = False
    if result.stdout:
        for line in result.stdout.split('\n'):
            if line.strip() and not line.startswith('??'):
                has_changes = True
                break

    return has_changes


def git_commit(message):
    """Create a git commit with message."""
    # Stage all changes
    subprocess.run(['git', 'add', '.'], capture_output=True)

    # Commit
    result = subprocess.run(
        ['git', 'commit', '-m', message],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        # Get commit hash
        hash_result = subprocess.run(
            ['git', 'rev-parse', 'HEAD'],
            capture_output=True,
            text=True
        )
        commit_hash = hash_result.stdout.strip()[:8]
        return commit_hash
    else:
        return None


def git_push():
    """Push changes to GitHub."""
    print("\n📤 Pushing to GitHub...")

    # Get current branch
    branch_result = subprocess.run(
        ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
        capture_output=True,
        text=True
    )
    branch = branch_result.stdout.strip()

    result = subprocess.run(
        ['git', 'push', 'origin', branch],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print(f"✅ Pushed to GitHub (branch: {branch})")
    else:
        print(f"❌ Push failed")
        if result.stderr:
            print(result.stderr)


def generate_colab_script(pull=True):
    """Generate Colab script for training."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    script_lines = [
        "#!/usr/bin/env python3",
        '"""',
        f'Auto-generated sync script - {timestamp}',
        '"""',
        "",
        "# Nano-Train Google Colab Training Script",
        "# Generated by scripts/sync_and_run.sh",
        "",
        "import subprocess",
        "import sys",
        "import os",
        "",
        "# Configuration",
        "REPO = \"https://github.com/lastweek/nano-train.git\"",
        "COLAB_NOTEBOOK = \"notebooks/train_in_colab.ipynb\"",
        "",
        "# Step 1: Pull latest code",
        "print(\"\\n🔄 Step 1: Pulling latest code from GitHub...\")",
        "result = subprocess.run(["git", "clone", "--depth", "1", REPO],",
        "                          capture_output=True, text=True)",
        "if result.returncode == 0:",
        "    print(\"✅ Code pulled successfully\")",
        "else:",
        "    print(\"❌ Failed to pull code\")",
        "    sys.exit(1)",
        "",
        "# Step 2: Install dependencies",
        "print(\"\\n📦 Step 2: Installing dependencies...\")",
        "subprocess.run([\"pip\", \"install\", \"-q\", \"torch\", \"torchvision\", \"tensorboard\", \"omegaconf\", \"tqdm\"])",
        "print(\"✅ Dependencies installed\")",
        "",
        "# Step 3: Run training notebook",
        "print(\"\\n🚀 Step 3: Starting training notebook...\")",
        "from google.colab import drive",
        "from google.colab import auth",
        "from google.colab import files",
        "",
        "# Mount Google Drive (optional - for checkpoint storage)",
        "# drive.mount('/content/drive')",
        "",
        "# Load and run the notebook",
        "files.upload(COLAB_NOTEBOOK)",
        "import subprocess",
        "result = subprocess.run(",
        "    [\"python3\", \"-m\", \"google.colab\", \"notebook\",",
        "     COLAB_NOTEBOOK,",
        "     --params", \"{}\".format({",
        "       \\\"repo_path\\\": \\\"nano-train\\\",",
        "       \\\"run_mode\\\": \\\"run\\\",",
        "     ],",
        "    capture_output=True, text=True",
        ")",
        "print(\"\\n✅ Training notebook launched!\")",
        "print(\"\\n📝 Checkpoint will be saved to: /content/nano-train/outputs/\")",
    ]

    script_path = f"scripts/colab_train_{timestamp}.py"
    os.makedirs('scripts', exist_ok=True)

    with open(script_path, 'w') as f:
        f.write('\n'.join(script_lines))

    # Make executable
    os.chmod(script_path, 0o755)

    print(f"\n✅ Generated: {script_path}")
    return script_path


def sync_and_run(push_first=True, pull=True, run_colab=True):
    """
    Main workflow: push changes, generate Colab script, run it.

    Args:
        push_first: If True, push before generating Colab script
        pull: If True, pull latest in Colab before training
        run_colab: If True, launch Colab notebook
    """
    print("\n" + "=" * 70)
    print("🚀 Nano-Train Sync & Run Workflow")
    print("=" * 70)

    # Check repo
    if not os.path.exists('.git'):
        print("❌ Not a git repository!")
        print("   Run: git init (or this script from repo root)")
        return

    os.chdir('/Volumes/CaseSensitive/nano-train')

    # Step 1: Check for changes and optionally push
    if push_first:
        print("\n📋 Step 1: Checking for local changes...")
        has_changes = check_git_changes()

        if has_changes:
            print("   Found uncommitted changes")
            commit_msg = f"Auto-commit: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
            commit_hash = git_commit(commit_msg)

            if commit_hash:
                print(f"   Committed: {commit_hash}")

                # Push to GitHub
                git_push()
        else:
            print("   No changes to push")

    # Step 2: Generate Colab training script
    print("\n📝 Step 2: Generating Colab training script...")
    script_path = generate_colab_script(pull=pull)

    # Step 3: Add script to git (so Colab can use it)
    print(f"\n📤 Step 3: Adding Colab script to git...")
    subprocess.run(['git', 'add', script_path], capture_output=True)
    commit_hash = git_commit(f"Add Colab training script ({datetime.now().strftime('%Y-%m-%d %H:%M')})")

    if commit_hash:
        print(f"   Committed: {commit_hash}")

    # Step 4: Push to GitHub
    print("\n📤 Step 4: Pushing to GitHub...")
    git_push()

    # Step 5: Run Colab
    if run_colab:
        print("\n🚀 Step 5: Launching Google Colab...")
        print("\n📋 INSTRUCTIONS FOR GOOGLE COLAB:")
        print("   1. Open this notebook in Google Colab")
        print("   2. The script will automatically:")
        print("      - Pull latest code from GitHub")
        print("      - Install dependencies")
        print("      - Launch the training notebook")
        print("   3. GPU will be used if available")
        print("   4. Checkpoints saved to /content/nano-train/outputs/")
        print("\n📝 Generated script:", script_path)
        print("\n" + "=" * 70)
        print("To run manually in Colab terminal:")
        print(f"   python {script_path}")
        print("\nOr run directly from the notebooks UI")
        print("\n" + "=" * 70)
    else:
        print("\n⏭ Skipped Colab launch (run_colab=False)")

    print("\n" + "=" * 70)
    print("✅ Workflow complete!")
    print("\n📍 Summary:")
    print("   • Changes committed and pushed to GitHub")
    print("   • Colab training script generated")
    if run_colab:
        print("   • Ready to run in Google Colab")
    else:
        print("   • To run: python scripts/sync_and_run.sh --run")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Sync code to GitHub and prepare Colab training"
    )
    parser.add_argument(
        '--no-push',
        action='store_true',
        help='Skip pushing to GitHub'
    )
    parser.add_argument(
        '--no-pull',
        action='store_true',
        help='Skip pulling latest in Colab'
    )
    parser.add_argument(
        '--no-colab',
        action='store_true',
        help='Skip launching Colab notebook'
    )

    args = parser.parse_args()

    # Run workflow
    sync_and_run(
        push_first=not args.no_push,
        pull=not args.no_pull,
        run_colab=not args.no_colab
    )


if __name__ == "__main__":
    main()
